```{r}
library(tidyverse)
library(readxl)
library(hrbrthemes)
library(grid)
library(png)
library(cowplot)
library(ggtext)

setwd(here::here())
```

```{r}
img <- png::read("data/ghibli2.png")
g_pic <- rasterGrob(img, interpolate=TRUE)
```

```{r}
df <- read_excel("data/ghibli_boxoffice.xlsx") %>%
  filter(is_magical == TRUE, !is.na(budget)) %>%
  mutate(title = fct_reorder(title, gross)) %>%
  pivot_longer(
    budget:gross
  ) %>%
  mutate(
    value = value/1e6,
    name = ifelse(name == "budget", "Budget", "Gross Revenue"),
    color = ifelse(name == "budget", "grey", "black")
  )
```

```{r}
df %>% head()
```

```{r}
options(repr.plot.width=12, repr.plot.height=8)

my_plot <- df %>% 
  ggplot(aes(x = title, y = value, fill = name)) +
  geom_col(width = c(0.9, 0.5)) +
  coord_flip() +
#   scale_color_manual(values = c("black", "peachpuff4")) +
  scale_fill_manual(values = c("grey", "cornflowerblue"), 
                    guide = "legend") +
  theme_ipsum(
    base_size = 20
  ) +
  labs(
    title = "Ghibli magical related movies by their budget and gross revenue",
    x = NULL,
    y = "mil. USD"
  ) +
  theme(
    plot.title = element_text(size = 28, color = "grey30"), 
    plot.title.position = "plot",
    plot.caption.position = "plot",
    plot.background = element_rect(fill = "seashell1", color = "seashell1"),
    panel.background = element_rect(fill = "seashell1", color = "seashell1"), 
    legend.position = c(0.9, 0.7),
    legend.title = element_blank()
  )
```

```{r}
suppressWarnings(
  ggdraw() +
    draw_plot(my_plot) +
    draw_image(
      "data/ghibli_logo.png", x = 0.28, y = -0.23, scale = 0.35
    )
)

ggsave("figures/day04.png", width = 12, height = 8)
```

```{r}

```
